### ISSUE TITLE
antlr4-tool 生成的没有getErrors方法

### ISSUE THREAD

**Issue by huangzhongping** [waltyou/spark-sql-online-editor#9]
// Generated from calculator.g4 by ANTLR 4.8
// jshint ignore: start
var antlr4 = require('antlr4/index');

// This class defines a complete listener for a parse tree produced by calculatorParser.
function calculatorListener() {
	antlr4.tree.ParseTreeListener.call(this);
	return this;
}

calculatorListener.prototype = Object.create(antlr4.tree.ParseTreeListener.prototype);
calculatorListener.prototype.constructor = calculatorListener;

// Enter a parse tree produced by calculatorParser#prog.
calculatorListener.prototype.enterProg = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#prog.
calculatorListener.prototype.exitProg = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#printExpr.
calculatorListener.prototype.enterPrintExpr = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#printExpr.
calculatorListener.prototype.exitPrintExpr = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#assign.
calculatorListener.prototype.enterAssign = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#assign.
calculatorListener.prototype.exitAssign = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#print.
calculatorListener.prototype.enterPrint = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#print.
calculatorListener.prototype.exitPrint = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#number.
calculatorListener.prototype.enterNumber = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#number.
calculatorListener.prototype.exitNumber = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#parens.
calculatorListener.prototype.enterParens = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#parens.
calculatorListener.prototype.exitParens = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#MulDiv.
calculatorListener.prototype.enterMulDiv = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#MulDiv.
calculatorListener.prototype.exitMulDiv = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#AddSub.
calculatorListener.prototype.enterAddSub = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#AddSub.
calculatorListener.prototype.exitAddSub = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#id.
calculatorListener.prototype.enterId = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#id.
calculatorListener.prototype.exitId = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#power.
calculatorListener.prototype.enterPower = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#power.
calculatorListener.prototype.exitPower = function(ctx) {
};

// Enter a parse tree produced by calculatorParser#factor.
calculatorListener.prototype.enterFactor = function(ctx) {
};

// Exit a parse tree produced by calculatorParser#factor.
calculatorListener.prototype.exitFactor = function(ctx) {
};

exports.calculatorListener = calculatorListener;

**Comment by waltyou** [comment]
antlr4-tool 不会生成`getErrors`方法的。这个方法是需要你自己在 ParseErrorListener 中定义的，看[这里](https://github.com/waltyou/spark-sql-online-editor/blob/master/src/sparkSql/ParseErrorListener.js#L20)。

**Comment by huangzhongping** [comment]
非常感谢，我现在遇到一个问题，antlr能自定义错误吗，我找不到在哪里

**Comment by waltyou** [comment]
不太明白你说的自定义错误是指什么。antlr相关的问题，你可以到antlr的仓库下找一找。
